version: '3.6'

services:
  db:
    image: postgres:9.6
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

  web:
    env_file: .env
    build:
      context: .
      args:
        - DJANGO_ENV=local
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/CK-Dabbawala
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
    external: true
