version: '3.0'

services:
  db:
    image: postgres:9.6
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

  web:
    build:
      context: .
    env_file: .env
