version: '3.0'

services:

  web:
    build:
      args:
        - DJANGO_ENV=staging-area
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/CK-Dabbawala
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
    external: true