# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 06:41
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(error_messages={'invalid': 'Máximo 50 caracteres. Letras, números y @/./+/-/_ únicamente.', 'unique': 'Ya existe un usuario con este nickname'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('phone_number', models.CharField(error_messages={'unique': 'Este número ya está registrado'}, max_length=13, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario con este email'}, max_length=254, unique=True)),
                ('address', models.CharField(error_messages={'unique': 'Ya existe un usuario con este email'}, max_length=255)),
                ('longitude', models.CharField(blank=True, default='0.0', max_length=30)),
                ('latitude', models.CharField(blank=True, default=0.0, max_length=30)),
                ('first_dabba', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
